2022-02-26 09:00:08 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration eskom_loadshedding which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-26 09:00:08 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-26 09:00:09 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-26 09:00:30 WARNING (MainThread) [homeassistant.setup] Setup of hassio is taking over 10 seconds.
2022-02-26 09:00:42 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2022-02-26 09:00:42 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2022-02-26 09:00:42 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2022-02-26 09:00:42 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2022-02-26 09:00:42 WARNING (MainThread) [homeassistant.setup] Setup of input_button is taking over 10 seconds.
2022-02-26 09:00:43 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
2022-02-26 09:00:43 WARNING (MainThread) [homeassistant.setup] Setup of input_datetime is taking over 10 seconds.
2022-02-26 09:00:43 WARNING (MainThread) [homeassistant.setup] Setup of timer is taking over 10 seconds.
2022-02-26 09:00:43 WARNING (MainThread) [homeassistant.setup] Setup of counter is taking over 10 seconds.
2022-02-26 09:00:53 WARNING (MainThread) [homeassistant.config_entries] Config entry 'P2500W series[081558]' for ipp integration not ready yet: Invalid response from API: Timeout occurred while connecting to IPP server.; Retrying in background
2022-02-26 09:00:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.eskom_loadshedding_stage (<class 'custom_components.eskom_loadshedding.sensor.EskomStageSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-26 09:00:58 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform adguard is taking over 10 seconds.
2022-02-26 09:00:58 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform adguard is taking over 10 seconds.
2022-02-26 09:01:05 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: Cannot connect to host 192.168.0.211:9939 ssl:default [Connect call failed ('192.168.0.211', 9939)]
2022-02-26 09:01:06 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: Cannot connect to host 192.168.0.210:22213 ssl:default [Connect call failed ('192.168.0.210', 22213)]
2022-02-26 09:01:45 ERROR (MainThread) [custom_components.hacs] Timeout of 20 reached while waiting for https://api.github.com/rate_limit
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 427, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Timeout of 20 reached while waiting for https://api.github.com/rate_limit
2022-02-26 09:02:07 WARNING (MainThread) [homeassistant.components.switch] Updating adguard switch took longer than the scheduled update interval 0:00:10
2022-02-26 09:02:08 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 580, in startup_tasks
    await self.recurring_tasks_installed()
  File "/config/custom_components/hacs/base.py", line 678, in recurring_tasks_installed
    await self.handle_critical_repositories()
  File "/config/custom_components/hacs/base.py", line 656, in handle_critical_repositories
    await critical_queue.execute()
  File "/config/custom_components/hacs/utils/queue_manager.py", line 69, in execute
    await asyncio.gather(*local_queue)
  File "/config/custom_components/hacs/base.py", line 736, in async_get_category_repositories
    repositories = await self.async_github_get_hacs_default_file(category)
  File "/config/custom_components/hacs/base.py", line 441, in async_github_get_hacs_default_file
    response = await self.async_github_api_method(
  File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Timeout of 20 reached while waiting for https://api.github.com/repos/hacs/default/contents/appdaemon
2022-02-26 09:02:08 WARNING (MainThread) [homeassistant.components.switch] Updating adguard switch took longer than the scheduled update interval 0:00:10
2022-02-26 09:02:13 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-02-26 09:02:13 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-02-26 09:02:13 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-02-26 09:02:13 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-02-26 09:02:13 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-02-26 09:02:14 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-02-26 09:02:17 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: Cannot connect to host 192.168.0.210:22213 ssl:default [Connect call failed ('192.168.0.210', 22213)]
2022-02-26 09:02:17 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-02-26 09:02:18 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: Cannot connect to host 192.168.0.210:22213 ssl:default [Connect call failed ('192.168.0.210', 22213)]
2022-02-26 10:01:01 ERROR (MainThread) [homeassistant.components.forecast_solar] Error requesting forecast_solar data: 500, message='Internal Server Error', url=URL('https://148.251.178.234/estimate/-26.921123/27.4479/30/142/2.0?time=iso8601&damping=0.0')
